### ISSUE TITLE
Cannot run tracing node with main branch

### ISSUE THREAD

**Issue by AsceticBear** [darwinia-network/darwinia-common#1394]
## Reproduce

Based on the main branch:
 
1. `cargo build --release --features evm-tracing`, then copy the compress wasm out, we need it later.
1. `cargo build --release`, Set up a local pangolin network with a local test script based on the main branch.
2.  Setup a dedicated trace node with:

```sh
./drml \
    -d data \
    --chain pangolin-local \
    --execution wasm \
    --ethapi-debug-targets=debug,trace \
    --wasm-runtime-overrides=overridden-runtimes/pangolin/wasms \    // Copy the build tracing runtime here
    --state-cache-size 0 \
    --rpc-port 10037 \
    --ws-port 10048 \
    --port 30437 \
    --unsafe-rpc-external \
    --unsafe-ws-external \
    --rpc-methods unsafe \
    --rpc-cors all
```

The output log:

```sh
2022-08-11 10:34:24 It isn't safe to expose RPC publicly without a proxy server that filters available set of RPC methods.    
2022-08-11 10:34:24 It isn't safe to expose RPC publicly without a proxy server that filters available set of RPC methods.    
2022-08-11 10:34:24 Darwinia Runtime Module Library    
2022-08-11 10:34:24 ✌️  version 2.8.19-41c55118-x86_64-linux-gnu    
2022-08-11 10:34:24 ❤️  by Darwinia Network <hello@darwinia.network>, 2018-2022    
2022-08-11 10:34:24 📋 Chain specification: Pangolin Local Testnet    
2022-08-11 10:34:24 🏷 Node name: tasteful-sofa-5159    
2022-08-11 10:34:24 👤 Role: FULL    
2022-08-11 10:34:24 💾 Database: RocksDb at data/chains/pangolin_dev/db/full    
2022-08-11 10:34:24 ⛓  Native runtime: Pangolin-28190 (Pangolin-0.tx0.au0)    
2022-08-11 10:34:26 Found wasm override in file: `Some("overridden-runtimes/pangolin/wasms/pangolin-v2.8.19-tracing-runtime.compact.compressed.wasm")`, version: Pangolin-28190 (Pangolin-0.tx0.au0)    
2022-08-11 10:34:26 `pallet_timestamp::UnixTime::now` is called at genesis, invalid value returned: 0    
2022-08-11 10:34:26 `pallet_timestamp::UnixTime::now` is called at genesis, invalid value returned: 0    
2022-08-11 10:34:26 `pallet_timestamp::UnixTime::now` is called at genesis, invalid value returned: 0    
2022-08-11 10:34:26 `pallet_timestamp::UnixTime::now` is called at genesis, invalid value returned: 0    
2022-08-11 10:34:26 [0] 💸 generated 4 npos voters, 4 from validators and 0 nominators    
2022-08-11 10:34:26 [0] 💸 generated 4 npos voters, 4 from validators and 0 nominators    
2022-08-11 10:34:26 [0] 💸 new validator set of size 4 has been processed for era 1    
2022-08-11 10:34:26 🔨 Initializing Genesis block/state (state: 0x4d2c…b94d, header-hash: 0x5f03…4d21)    
2022-08-11 10:34:26 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.    
2022-08-11 10:34:28 length of a bounded vector in scope decode is not respected.    
2022-08-11 10:34:28 ⏱  Loaded block-time = 6s from block 0x5f03d4993a21bd7bff13ef983115247077d8909154e36379740cf5c4737e4d21    
2022-08-11 10:34:28 👶 Creating empty BABE epoch changes on what appears to be first startup.    
2022-08-11 10:34:28 🏷 Local node identity is: 12D3KooWK9yKz2PWhnacQvJRD5QqH77HBTPN9w13D2JjGnMTh6XZ    
2022-08-11 10:34:28 DVM mapping worker starts syncing from 0    
2022-08-11 10:34:28 📦 Highest known block at #0    
2022-08-11 10:34:28 Listening for new connections on 0.0.0.0:10048.    
2022-08-11 10:34:28 length of a bounded vector in scope decode is not respected.    
2022-08-11 10:34:28 length of a bounded vector in scope decode is not respected.    
2022-08-11 10:34:28 panicked at 'Digest item must match that calculated.', /home/runner/.cargo/git/checkouts/substrate-a7fa553ead635512/1df7fe5/frame/executive/src/lib.rs:497:13    
2022-08-11 10:34:28 Block prepare storage changes error:
RuntimeApiError(Application(Execution(Other("Wasm execution trapped: wasm trap: wasm `unreachable` instruction executed\nwasm backtrace:\n    0: 0x9156 - <unknown>!rust_begin_unwind\n    1: 0x28a3 - <unknown>!core::panicking::panic_fmt::h781687f2782526ba\n    2: 0x8569 - <unknown>!core::panicking::panic::h7e19f14ea3257c22\n    3: 0x24d3fb - <unknown>!Core_execute_block\n"))))    
2022-08-11 10:34:28 💔 Error importing block 0x7809ce392f317a697b77489d80191e8705768835eb8832c9b033bb13cdbc49c2: Err(Other(ClientImport("Import failed: Error at calling runtime api: Execution failed: Other(\"Wasm execution trapped: wasm trap: wasm `unreachable` instruction executed\\nwasm backtrace:\\n    0: 0x9156 - <unknown>!rust_begin_unwind\\n    1: 0x28a3 - <unknown>!core::panicking::panic_fmt::h781687f2782526ba\\n    2: 0x8569 - <unknown>!core::panicking::panic::h7e19f14ea3257c22\\n    3: 0x24d3fb - <unknown>!Core_execute_block\\n\")")))    
2022-08-11 10:34:28 💔 Error importing block 0x389fdbf829aa2b7df457f759d166887d398e1bc3947b272ab57a95c5b0122a83: Err(UnknownParent)    
2022-08-11 10:34:28 length of a bounded vector in scope decode is not respected.    
2022-08-11 10:34:28 length of a bounded vector in scope decode is not respected.    
2022-08-11 10:34:28 panicked at 'Digest item must match that calculated.', /home/runner/.cargo/git/checkouts/substrate-a7fa553ead635512/1df7fe5/frame/executive/src/lib.rs:497:13    
2022-08-11 10:34:28 Block prepare storage changes error:
RuntimeApiError(Application(Execution(Other("Wasm execution trapped: wasm trap: wasm `unreachable` instruction executed\nwasm backtrace:\n    0: 0x9156 - <unknown>!rust_begin_unwind\n    1: 0x28a3 - <unknown>!core::panicking::panic_fmt::h781687f2782526ba\n    2: 0x8569 - <unknown>!core::panicking::panic::h7e19f14ea3257c22\n    3: 0x24d3fb - <unknown>!Core_execute_block\n"))))    
2022-08-11 10:34:28 💔 Error importing block 0x7809ce392f317a697b77489d80191e8705768835eb8832c9b033bb13cdbc49c2: Err(Other(ClientImport("Import failed: Error at calling runtime api: Execution failed: Other(\"Wasm execution trapped: wasm trap: wasm `unreachable` instruction executed\\nwasm backtrace:\\n    0: 0x9156 - <unknown>!rust_begin_unwind\\n    1: 0x28a3 - <unknown>!core::panicking::panic_fmt::h781687f2782526ba\\n    2: 0x8569 - <unknown>!core::panicking::panic::h7e19f14ea3257c22\\n    3: 0x24d3fb - <unknown>!Core_execute_block\\n\")")))    
2022-08-11 10:34:28 💔 Error importing block 0x95fde7319a1f096049544fb83236cd41b4fd4be9d6abcf8115a786c2cef4feef: Err(UnknownParent)    
2022-08-11 10:34:29 length of a bounded vector in scope decode is not respected.    
2022-08-11 10:34:29 length of a bounded vector in scope decode is not respected.    
2022-08-11 10:34:29 panicked at 'Digest item must match that calculated.', /home/runner/.cargo/git/checkouts/substrate-a7fa553ead635512/1df7fe5/frame/executive/src/lib.rs:497:13    
2022-08-11 10:34:29 Block prepare storage changes error:
RuntimeApiError(Application(Execution(Other("Wasm execution trapped: wasm trap: wasm `unreachable` instruction executed\nwasm backtrace:\n    0: 0x9156 - <unknown>!rust_begin_unwind\n    1: 0x28a3 - <unknown>!core::panicking::panic_fmt::h781687f2782526ba\n    2: 0x8569 - <unknown>!core::panicking::panic::h7e19f14ea3257c22\n    3: 0x24d3fb - <unknown>!Core_execute_block\n"))))    
2022-08-11 10:34:29 💔 Error importing block 0x7809ce392f317a697b77489d80191e8705768835eb8832c9b033bb13cdbc49c2: Err(Other(ClientImport("Import failed: Error at calling runtime api: Execution failed: Other(\"Wasm execution trapped: wasm trap: wasm `unreachable` instruction executed\\nwasm backtrace:\\n    0: 0x9156 - <unknown>!rust_begin_unwind\\n    1: 0x28a3 - <unknown>!core::panicking::panic_fmt::h781687f2782526ba\\n    2: 0x8569 - <unknown>!core::panicking::panic::h7e19f14ea3257c22\\n    3: 0x24d3fb - <unknown>!Core_execute_block\\n\")")))    
2022-08-11 10:34:29 💔 Error importing block 0x389fdbf829aa2b7df457f759d166887d398e1bc3947b272ab57a95c5b0122a83: Err(UnknownParent)    
2022-08-11 10:34:29 💔 Error importing block 0x95fde7319a1f096049544fb83236cd41b4fd4be9d6abcf8115a786c2cef4feef: Err(UnknownParent)    
2022-08-11 10:34:29 length of a bounded vector in scope decode is not respected.    
2022-08-11 10:34:29 length of a bounded vector in scope decode is not respected.    
2022-08-11 10:34:29 panicked at 'Digest item must match that calculated.', /home/runner/.cargo/git/checkouts/substrate-a7fa553ead635512/1df7fe5/frame/executive/src/lib.rs:497:13    
2022-08-11 10:34:29 Block prepare storage changes error:
RuntimeApiError(Application(Execution(Other("Wasm execution trapped: wasm trap: wasm `unreachable` instruction executed\nwasm backtrace:\n    0: 0x9156 - <unknown>!rust_begin_unwind\n    1: 0x28a3 - <unknown>!core::panicking::panic_fmt::h781687f2782526ba\n    2: 0x8569 - <unknown>!core::panicking::panic::h7e19f14ea3257c22\n    3: 0x24d3fb - <unknown>!Core_execute_block\n"))))    
2022-08-11 10:34:29 💔 Error importing block 0x7809ce392f317a697b77489d80191e8705768835eb8832c9b033bb13cdbc49c2: Err(Other(ClientImport("Import failed: Error at calling runtime api: Execution failed: Other(\"Wasm execution trapped: wasm trap: wasm `unreachable` instruction executed\\nwasm backtrace:\\n    0: 0x9156 - <unknown>!rust_begin_unwind\\n    1: 0x28a3 - <unknown>!core::panicking::panic_fmt::h781687f2782526ba\\n    2: 0x8569 - <unknown>!core::panicking::panic::h7e19f14ea3257c22\\n    3: 0x24d3fb - <unknown>!Core_execute_block\\n\")")))    
2022-08-11 10:34:33 💤 Idle (0 peers), best: #0 (0x5f03…4d21), finalized #0 (0x5f03…4d21), ⬇ 124.0kiB/s ⬆ 7.9kiB/s  
```

I have no idea about this now. I'll try to reproduce this with the older release version, especially the currently onchain version.

**Comment by AurevoirXavier** [comment]
You are using two different version nodes.

From the log `2022-08-11 10:34:24 ✌️  version 2.8.19-41c55118-x86_64-linux-gnu`, I know you are in the main branch.
From the log `2022-08-11 10:34:28 length of a bounded vector in scope decode is not respected.`, I know the version you are trying to sync from is not included https://github.com/darwinia-network/darwinia-common/commit/2c6ddabaa245622f8f6b3f9ba4971ce16de35d16.

Two different commits are both under spec version 28190.
This is why you get this error.

**Comment by AsceticBear** [comment]
> cargo build --release --features evm-tracing, then copy the compress wasm out, we need it later.

A bit confused. I generate the override runtime by compiling the main branch first, this should include https://github.com/darwinia-network/darwinia-common/commit/2c6ddabaa245622f8f6b3f9ba4971ce16de35d16.

**Comment by AurevoirXavier** [comment]
I don't know. Maybe some mistakes.

But I'm sure if you are using the latest code, you won't see `length of a bounded vector in scope decode is not respected`.(I also test this on my local machine)

**Comment by AsceticBear** [comment]
I'll try to clean the artifact and reproduce it. I'll feedback later

**Comment by AurevoirXavier** [comment]
How about the `overridden-runtimes/pangolin/wasms`?

**Comment by AsceticBear** [comment]
> How about the overridden-runtimes/pangolin/wasms? Did you regenerate it?

When I test this based on the main branch, I copied the generated tracing runtime to `overridden-runtimes/pangolin/wasms` and replace the `pangolin-v2.8.19-tracing-runtime.compact.compressed.wasm`.

> The CI's release is also for v2.8.19, not for the main branch.

I know about this. We should use the newest wasm overrides file instead of that one from runtime-overrides in the test above.

**Comment by AsceticBear** [comment]
> ```shell
> Found wasm override in file: `Some("overridden-runtimes/pangolin/wasms/pangolin-v2.8.19-tracing-runtime.compact.compressed.wasm")`, version: Pangolin-28190 (Pangolin-0.tx0.au0) 
> ```

Did you use `--wasm-runtime-overrides=overridden-runtimes/pangolin/wasms` or clean the data? I did not see something like:

```sh
2022-08-11 10:34:26 Found wasm override in file: `Some("overridden-runtimes/pangolin/wasms/pangolin-v2.8.19-tracing-runtime.compact.compressed.wasm")`, version: Pangolin-28190 (Pangolin-0.tx0.au0)    
   
```

**Comment by AurevoirXavier** [comment]
Here's a simple steps to test:

```
cargo build --release --features evm-tracing
tests/local-testnet/deploy.sh pangolin
target/release/drml --tmp --chain pangolin-local --execution wasm --ethapi-debug-targets debug,trace --wasm-runtime-overrides target/release/wbuild/pangolin-runtime/ --state-cache-size 0

2022-08-11 11:47:30 Darwinia Runtime Module Library    
2022-08-11 11:47:30 ✌️  version 2.8.19-41c55118-x86_64-linux-gnu    
2022-08-11 11:47:30 ❤️  by Darwinia Network <hello@darwinia.network>, 2018-2022    
2022-08-11 11:47:30 📋 Chain specification: Pangolin Local Testnet    
2022-08-11 11:47:30 🏷 Node name: unequal-account-5034    
2022-08-11 11:47:30 👤 Role: FULL    
2022-08-11 11:47:30 💾 Database: RocksDb at /tmp/substratemTRLcj/chains/pangolin_dev/db/full    
2022-08-11 11:47:30 ⛓  Native runtime: Pangolin-28190 (Pangolin-0.tx0.au0)    
2022-08-11 11:47:31 Found wasm override in file: `Some("target/release/wbuild/pangolin-runtime/pangolin_runtime.compact.compressed.wasm")`, version: Pangolin-28190 (Pangolin-0.tx0.au0)    
2022-08-11 11:47:31 `pallet_timestamp::UnixTime::now` is called at genesis, invalid value returned: 0    
2022-08-11 11:47:31 `pallet_timestamp::UnixTime::now` is called at genesis, invalid value returned: 0    
2022-08-11 11:47:31 `pallet_timestamp::UnixTime::now` is called at genesis, invalid value returned: 0    
2022-08-11 11:47:31 `pallet_timestamp::UnixTime::now` is called at genesis, invalid value returned: 0    
2022-08-11 11:47:31 [0] 💸 generated 4 npos voters, 4 from validators and 0 nominators    
2022-08-11 11:47:31 [0] 💸 generated 4 npos voters, 4 from validators and 0 nominators    
2022-08-11 11:47:31 [0] 💸 new validator set of size 4 has been processed for era 1    
2022-08-11 11:47:31 🔨 Initializing Genesis block/state (state: 0x5903…112a, header-hash: 0xd0f0…7f58)    
2022-08-11 11:47:31 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.    
2022-08-11 11:47:32 ⏱  Loaded block-time = 6s from block 0xd0f0f642116424693a5da229ba2366f94385be089ba5a1dc9e13246c23fb7f58    
2022-08-11 11:47:32 👶 Creating empty BABE epoch changes on what appears to be first startup.    
2022-08-11 11:47:32 🏷 Local node identity is: 12D3KooWMVrjG7RXe6Vs9Ps9mjrVNRcwjPWm1p1JbX8sKchtyTH1    
2022-08-11 11:47:32 DVM mapping worker starts syncing from 0    
2022-08-11 11:47:32 📦 Highest known block at #0    
2022-08-11 11:47:32 Listening for new connections on 127.0.0.1:9944.    
2022-08-11 11:47:32 Invalid raw message root: [], return.    
2022-08-11 11:47:32 Invalid raw message root: [], return.    
2022-08-11 11:47:36 ✨ Imported #27 (0x8956…b8ba)    
2022-08-11 11:47:37 💤 Idle (4 peers), best: #27 (0x8956…b8ba), finalized #24 (0x4789…690e), ⬇ 7.8kiB/s ⬆ 3.7kiB/s    
2022-08-11 11:47:42 ✨ Imported #28 (0xa6c3…cf10)    
2022-08-11 11:47:42 💤 Idle (4 peers), best: #28 (0xa6c3…cf10), finalized #25 (0xdae1…8f5e), ⬇ 6.0kiB/s ⬆ 3.8kiB/s
```

**Comment by AsceticBear** [comment]
My tracing runtime was copied to the wrong directory before, which caused this error. Thanks for your help.
