### ISSUE TITLE
[Dvm] Node crash when call `web3.eth.Contract.once` 

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-common#419]
## Test
```
mocha test-constract-log.js
```

## Node output
```
Dec 28 23:48:06.036 ERROR WS Error <Io(Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" })>

====================

Version: 1.0.2-da11d72-x86_64-macos

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/panicking.rs:581:17
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/panicking.rs:484:9
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/sys_common/backtrace.rs:153:18
   6: rust_begin_unwind
             at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/panicking.rs:483:5
   7: core::panicking::panic_fmt
             at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/core/src/panicking.rs:85:14
   8: core::panicking::panic_bounds_check
             at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/core/src/panicking.rs:62:5
   9: dvm_rpc_core_primitives::filter::FilteredParams::replace
  10: dvm_rpc_core_primitives::filter::FilteredParams::filter_topics
  11: dvm_rpc::eth_pubsub::SubscriptionResult::logs
  12: <T as futures_util::fns::FnMut1<A>>::call_mut
  13: <futures_util::stream::stream::FlatMap<St,U,F> as futures_core::stream::Stream>::poll_next
  14: <futures_util::compat::compat03as01::Compat<St> as futures::stream::Stream>::poll
  15: <futures::sink::send_all::SendAll<T,U> as futures::future::Future>::poll
  16: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  17: <futures::future::select::Select<A,B> as futures::future::Future>::poll
  18: futures::future::chain::Chain<A,B,C>::poll
  19: futures::task_impl::std::set
  20: futures::task_impl::Spawn<T>::poll_fn_notify
  21: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  22: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  23: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  25: tokio::runtime::task::core::Core<T,S>::poll
  26: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
  27: tokio::runtime::task::raw::poll
  28: std::thread::local::LocalKey<T>::with
  29: tokio::runtime::thread_pool::worker::Context::run_task
  30: tokio::runtime::thread_pool::worker::Context::run
  31: tokio::macros::scoped_tls::ScopedKey<T>::set
  32: tokio::runtime::thread_pool::worker::run
  33: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  34: tokio::runtime::task::core::Core<T,S>::poll
  35: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  36: tokio::runtime::task::harness::Harness<T,S>::poll
  37: tokio::runtime::blocking::pool::Inner::run
  38: tokio::runtime::context::enter
  39: std::sys_common::backtrace::__rust_begin_short_backtrace
  40: core::ops::function::FnOnce::call_once{{vtable.shim}}
  41: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/alloc/src/boxed.rs:1042:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/alloc/src/boxed.rs:1042:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/sys/unix/thread.rs:87:17
  42: __pthread_start


Thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 1 but the index is 1', primitives/dvm-rpc-core/src/filter.rs:188

```

**Comment by AsceticBear** [comment]
Please give me more info about `test-constract-log.js`.

**Comment by hujw77** [comment]
https://github.com/darwinia-network/darwinia-common/blob/056d2c5aff9c14758e21acbf5df0faf677571e29/script_tests/tests/contract/test-constract-log.js#L59

It may be caused by a wrong script, but the node should not crash.

**Comment by AsceticBear** [comment]
@hujw77  I tried to reproduce this panic case following the command below, but this test passed. Could you please add more info about this case or run it again to check if the test would be failed. 

```sh
$ /target/release/drml --dev --tmp
$ ./node_modules/mocha/bin/mocha tests/2_test-constract-log.js
```

![image](https://user-images.githubusercontent.com/11801722/103396566-f55e0f00-4b6e-11eb-93be-213020440eab.png)
